import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import OpenAI from 'openai';
dotenv.config();
const app=express(); app.use(cors()); app.use(express.json({limit:'8mb'}));
const PORT=process.env.PORT||8787;
const TOKEN_URL='https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token';
const PROCESS_URL='https://sh.dataspace.copernicus.eu/process/v1';
const CATALOG_URL='https://sh.dataspace.copernicus.eu/catalog/v1/search';
let tokenCache={token:null,exp:0};
const scripts={
 truecolor:`//VERSION=3\nfunction setup(){return {input:['B02','B03','B04'],output:{bands:3,sampleType:'UINT8'}}}\nfunction evaluatePixel(s){return [Math.min(255,Math.max(0,255*2.5*s.B04)),Math.min(255,Math.max(0,255*2.5*s.B03)),Math.min(255,Math.max(0,255*2.5*s.B02))]}`,
 ndvi:`//VERSION=3\nfunction setup(){return {input:['B04','B08'],output:{bands:3,sampleType:'UINT8'}}}\nfunction evaluatePixel(s){let n=(s.B08-s.B04)/(s.B08+s.B04);let v=(n+1)/2;return [Math.round(255*(1-v)),Math.round(255*Math.min(1,v*1.6)),35]}`,
 ndwi:`//VERSION=3\nfunction setup(){return {input:['B03','B08'],output:{bands:3,sampleType:'UINT8'}}}\nfunction evaluatePixel(s){let n=(s.B03-s.B08)/(s.B03+s.B08);let v=(n+1)/2;return [35,Math.round(180*(1-v)+60),Math.round(255*v)]}`,
 urban:`//VERSION=3\nfunction setup(){return {input:['B08','B11'],output:{bands:3,sampleType:'UINT8'}}}\nfunction evaluatePixel(s){let n=(s.B11-s.B08)/(s.B11+s.B08);let v=Math.max(0,Math.min(1,(n+0.5)/1));return [Math.round(255*v),Math.round(190*(1-v)),35]}`
};
function num(v,n){const x=Number(v);if(!Number.isFinite(x))throw Error(n+' must be a number');return x}
function bbox(lat,lon,d=.045){return [lon-d,lat-d,lon+d,lat+d]}
function range(date){if(!date||date==='latest'){const to=new Date(),from=new Date(to-365*86400000);return {from:from.toISOString(),to:to.toISOString()}}const from=new Date(date+'T00:00:00Z');if(isNaN(from))throw Error('Invalid date');return {from:from.toISOString(),to:new Date(from.getTime()+35*86400000).toISOString()}}
async function token(){if(tokenCache.token&&tokenCache.exp>Date.now()+60000)return tokenCache.token;if(!process.env.COPERNICUS_CLIENT_ID||!process.env.COPERNICUS_CLIENT_SECRET)throw Error('Copernicus credentials are not configured');const body=new URLSearchParams({grant_type:'client_credentials',client_id:process.env.COPERNICUS_CLIENT_ID,client_secret:process.env.COPERNICUS_CLIENT_SECRET});const r=await fetch(TOKEN_URL,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw Error('Copernicus authentication failed');const j=await r.json();tokenCache={token:j.access_token,exp:Date.now()+Number(j.expires_in||300)*1000};return tokenCache.token}
app.get('/api/health',(q,s)=>s.json({ok:true,service:'SatQuery AI'}));
app.get('/api/geocode',async(q,s)=>{try{const text=String(q.query.q||'').trim();if(!text)throw Error('Search query required');const u=new URL('https://nominatim.openstreetmap.org/search');u.searchParams.set('q',text);u.searchParams.set('format','jsonv2');u.searchParams.set('limit','1');const r=await fetch(u,{headers:{'User-Agent':'SatQueryAI/1.0'}});const a=(await r.json())[0];if(!a)throw Error('Location not found');s.json({display:a.display_name,lat:+a.lat,lon:+a.lon,area_km2:a.boundingbox?Math.abs((a.boundingbox[2]-a.boundingbox[0])*(a.boundingbox[3]-a.boundingbox[1]))*12321:undefined})}catch(e){s.status(400).json({error:e.message})}});
app.get('/api/weather',async(q,s)=>{try{const lat=num(q.query.lat,'lat'),lon=num(q.query.lon,'lon');const u=new URL('https://api.open-meteo.com/v1/forecast');u.searchParams.set('latitude',lat);u.searchParams.set('longitude',lon);u.searchParams.set('current','temperature_2m,wind_speed_10m,relative_humidity_2m');u.searchParams.set('timezone','auto');const j=await (await fetch(u)).json();s.json({temperature:j.current?.temperature_2m,wind:j.current?.wind_speed_10m,humidity:j.current?.relative_humidity_2m,elevation:j.elevation})}catch(e){s.status(400).json({error:e.message})}});
app.get('/api/satellite',async(q,s)=>{try{const lat=num(q.query.lat,'lat'),lon=num(q.query.lon,'lon'),type=q.query.type||'truecolor';const t=await token(),rge=range(q.query.date);const body={input:{bounds:{properties:{crs:'http://www.opengis.net/def/crs/OGC/1.3/CRS84'},bbox:bbox(lat,lon)},data:[{type:'sentinel-2-l2a',dataFilter:{timeRange:rge,mosaickingOrder:'leastCC',maxCloudCoverage:80}}]},output:{width:900,height:650,responses:[{identifier:'default',format:{type:'image/jpeg',quality:88}}]},evalscript:scripts[type]||scripts.truecolor};const r=await fetch(PROCESS_URL,{method:'POST',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error('Satellite processing failed '+r.status);const b=Buffer.from(await r.arrayBuffer()).toString('base64');s.json({url:'data:image/jpeg;base64,'+b,type,date:q.query.date||'latest',source:'Copernicus Sentinel-2 L2A'})}catch(e){s.status(400).json({error:e.message})}});
app.get('/api/catalog',async(q,s)=>{try{const lat=num(q.query.lat,'lat'),lon=num(q.query.lon,'lon'),days=Math.min(3650,Math.max(1,+(q.query.days||365)));const end=new Date(),start=new Date(end-days*86400000);const r=await fetch(CATALOG_URL,{method:'POST',headers:{Authorization:'Bearer '+await token(),'Content-Type':'application/json'},body:JSON.stringify({bbox:bbox(lat,lon),datetime:start.toISOString()+'/'+end.toISOString(),collections:['sentinel-2-l2a'],limit:25})});if(!r.ok)throw Error('Catalog failed '+r.status);const j=await r.json();s.json({count:j.features?.length||0,features:(j.features||[]).map(x=>({id:x.id,date:x.properties?.datetime,cloud:x.properties?.['eo:cloud_cover']}))})}catch(e){s.status(400).json({error:e.message})}});
app.get('/api/analysis',async(q,s)=>{try{const out={};for(const type of ['ndvi','ndwi','urban']){const u=new URL('/api/satellite','http://localhost:'+PORT);u.searchParams.set('lat',q.query.lat);u.searchParams.set('lon',q.query.lon);u.searchParams.set('date',q.query.date||'latest');u.searchParams.set('type',type);const r=await fetch(u);if(r.ok)out[type]=(await r.json()).url}s.json({images:out,note:'Signals are spectral remote-sensing visualizations; interpret with uncertainty.'})}catch(e){s.status(400).json({error:e.message})}});
app.post('/api/ai',async(q,s)=>{try{if(!process.env.GROQ_API_KEY)throw Error('GROQ_API_KEY is not configured');const {question,location}=q.body;const client=new OpenAI({apiKey:process.env.GROQ_API_KEY,baseURL:'https://api.groq.com/openai/v1'});const prompt=`You are SatQuery AI, an Earth-observation analyst. Location: ${location?.display} (${location?.lat},${location?.lon}). Question: ${question}. Do not invent measurements. Distinguish visible evidence, inference and uncertainty.`;const r=await client.chat.completions.create({model:process.env.GROQ_MODEL||'openai/gpt-oss-120b',messages:[{role:'user',content:prompt}]});s.json({answer:r.choices[0]?.message?.content||'Groq returned an empty answer.'})}catch(e){s.status(400).json({error:e.message})}});
app.listen(PORT,()=>console.log('SatQuery API on '+PORT));
